# Generated by Django 3.2.7 on 2021-09-15 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifeadminapi', '0002_auto_20210915_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='householduser',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='householduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
